FROM postgres:9.6-alpine

LABEL description="Postgres developer setup for info-message-service"
LABEL vendor="Jon Larsson"
LABEL license="The MIT License (MIT)"

COPY init.sh /docker-entrypoint-initdb.d/